<?php

return [
    "title" => "Ensemble de meubles de salle de bains",
    "subTitle" => "Meubles de salle de bain de style moderne",
    "bathroomCabinetWithWashbasin" => "Meuble de salle de bain suspendu pour lavabo",
    "bathroomCabinetWithWashbasinDesc" => "Ce meuble sous vasque avec un élégant plateau en chêne verni est parfait pour ceux qui apprécient les intérieurs stylés et intemporels. Sa façade en MDF courbé, recouverte d\'un vernis brillant, allie harmonieusement un look moderne à une élégance subtile. La poignée intégrée ajoute une touche de légèreté au design, et le meuble s\'harmonise parfaitement avec les lavabos à poser ou encastrés. Ce meuble rehausse non seulement l\'esthétique de la salle de bains, mais crée également un espace cohérent avec un haut niveau visuel.",
    "solidityAndPrecisionOfWorkmanship" => "Solidité et précision de fabrication",
    "solidityAndPrecisionOfWorkmanshipDesc" => "Son aspect saisissant est soutenu par une technologie de pointe. La façade est recouverte d\'un stratifié HPL durable et d\'un vernis brillant, résistant à l\'humidité et aux rayures. L\'intérieur est équipé de coulisses BLUM Tandem avec un système de fermeture en douceur, couvert par une garantie à vie. L\'ensemble est logé dans un corps en panneaux de meubles gris cendré durable, protégé par des chants en ABS. Cette solution conçue avec précision garantit non seulement une grande facilité d\'utilisation, mais aussi une longue durée de vie.",
    "bathroomCabinetsWithShelves" => "Armoires de salle de bains murales avec étagères",
    "bathroomCabinetsWithShelvesDesc" => "L\'armoire est équipée de portes universelles qui peuvent être montées à gauche ou à droite. Cette solution vous permet d\'adapter parfaitement la disposition des meubles à votre espace, quelle que soit sa configuration. Ici, fonctionnalité et esthétique vont de pair.",
    "bathroomCabinetsWithShelvesWithCountertop" => "Armoires de salle de bains murales avec étagères et plan de travail",
    "bathroomCabinetsWithShelvesWithCountertopDesc" => "La conception astucieuse de l\'armoire permet de monter la porte à gauche ou à droite, offrant ainsi de nombreuses possibilités d\'agencement. Un plan de travail en chêne verni complète le look et ajoute une touche d\'élégance. L\'armoire convient ainsi aussi bien aux salles de bains classiques que modernes, alliant beauté et fonctionnalité.",
    "bathroomSetDescOne" => "La collection a été créée pour ceux qui ne veulent pas choisir parmi les options disponibles, mais préfèrent les définir eux-mêmes. Nous proposons une personnalisation complète de l'ensemble de meubles de salle de bains, afin de créer un espace qui ne suit pas les tendances. Il les définit.",
    "bathroomSetDescTwo" => "L'une de ses caractéristiques distinctives est la possibilité de finir les façades avec des surfaces entièrement chromées. Leur finition miroir devient plus qu'un simple élément fonctionnel : elle se transforme en une déclaration décorative raffinée. En choisissant votre propre couleur de chrome, vous déterminez le ton de votre intérieur. L'argent froid souligne la modernité. Le cuivre noble apporte de la chaleur. Le noir profond crée un contraste et une touche dramatique.",
    "bathroomSetDescThree" => "Chaque détail peut être adapté à votre vision. Dans nos collections pour salle de bains, l'individualité n'est pas un supplément. C'est la norme.",
];
