<?php

return [
    "title" => "Badezimmermöbel-Set",
    "subTitle" => "Moderner Stil für Badezimmerschränke",
    "bathroomCabinetWithWashbasin" => "Wandhängender Badezimmerschrank für den Waschtisch",
    "bathroomCabinetWithWashbasinDesc" => "Dieser Waschtischunterschrank mit einer eleganten Oberfläche aus lackierter Eiche ist perfekt für alle, die Wert auf stilvolle und zeitlose Innenräume legen. Seine gebogene MDF-Front mit glänzender Lackierung verbindet auf harmonische Weise einen modernen Look mit subtiler Eleganz. Der integrierte Griff verleiht dem Design eine gewisse Leichtigkeit, und der Unterschrank passt perfekt zu Aufsatz- und Einbauwaschbecken. Dieses Möbelstück wertet nicht nur die Ästhetik des Badezimmers auf, sondern schafft auch einen einheitlichen Raum mit hohem optischem Anspruch.",
    "solidityAndPrecisionOfWorkmanship" => "Solide und präzise Verarbeitung",
    "solidityAndPrecisionOfWorkmanshipDesc" => "Die auffällige Optik wird durch fortschrittliche Technologie untermauert. Die Front ist mit strapazierfähigem HPL-Laminat und hochglänzendem Lack versehen, der gegen Feuchtigkeit und Kratzer beständig ist. Im Inneren befinden sich BLUM-Tandem-Führungen mit Soft-Close-System, die mit einer lebenslangen Garantie versehen sind. Die gesamte Einheit ist in einem robusten Möbelkorpus aus askegrauem Möbelspan mit ABS-Kanten geschützt. Diese präzise konstruierte Lösung gewährleistet nicht nur eine einfache Bedienung, sondern auch eine lange Lebensdauer.",
    "bathroomCabinetsWithShelves" => "Wandhängende Badezimmerschränke mit Regalen",
    "bathroomCabinetsWithShelvesDesc" => "Der Schrank verfügt über universelle Türen, die sowohl links als auch rechts montiert werden können. So können Sie die Möbel unabhängig von der Raumaufteilung perfekt an Ihren Platzbedarf anpassen. Funktionalität und Ästhetik gehen hier Hand in Hand.",
    "bathroomCabinetsWithShelvesWithCountertop" => "Wandhängende Badezimmerschränke mit Regalen und Arbeitsplatte",
    "bathroomCabinetsWithShelvesWithCountertopDesc" => "Das clevere Design des Schranks ermöglicht die Montage der Tür auf beiden Seiten – links oder rechts – und bietet so flexible Gestaltungsmöglichkeiten. Eine lackierte Eichenholz-Arbeitsplatte rundet das Bild ab und verleiht dem Schrank einen Hauch von Eleganz. Damit eignet sich der Schrank sowohl für klassische als auch für moderne Badezimmer und verbindet Schönheit mit Funktionalität.",
    "bathroomSetDescOne" => "Die Kollektion wurde für diejenigen geschaffen, die sich nicht mit den verfügbaren Optionen zufrieden geben möchten, sondern lieber selbst entscheiden. Wir bieten eine vollständige Individualisierung der Badezimmermöbel und schaffen so einen Raum, der nicht Trends folgt, sondern sie setzt.",
    "bathroomSetDescTwo" => "Eines der charakteristischen Merkmale ist die Möglichkeit, die Fronten vollständig verchromt auszuführen. Ihre spiegelglatte Oberfläche ist mehr als nur ein funktionales Element – sie wird zu einem raffinierten dekorativen Statement. Durch die Auswahl Ihrer eigenen Chromfarbe bestimmen Sie den Ton des Interieurs. Kühles Silber unterstreicht die Modernität. Edles Kupfer sorgt für Wärme. Tiefes Schwarz schafft Kontraste und Dramatik.",
    "bathroomSetDescThree" => "Jedes Detail kann ganz nach Ihren Vorstellungen gestaltet werden. In unseren Badkollektionen ist Individualität kein Zusatz, sondern Standard.",
];
