<?php
declare(strict_types=1);

return [
  'availableLanguage' => [
      'de',
      'pl',
      'uk',
      'es',
      'it',
      'fr',
      'nl',
      'no',
      'se',
      'fi',
      'dk',
      'sk',
      'ae',
      'cs',
      'bg',
      'hu',
      'ro',
      'hr',
      'lt',
      'gr',
      'ee',
      'pt',
      'ru',
      'tr',
      'ua',
  ],

  'defaultLanguage' => env('APP_LOCALE', 'de'),
  'groupLanguageByCountryIso' => [
    'SH' => 'uk',
    'IE' => 'uk',
    'AU' => 'uk',
    'CA' => 'uk',
    'US' => 'uk',
    'USA' => 'uk',
    'GA' => 'uk',
    'GB' => 'uk',
    'DE' => 'de',
    'AT' => 'de',
    'BE' => 'fr',
    'FR' => 'fr',
    'ES' => 'es',
    'IT' => 'it',
    'PL' => 'pl',
    'NL' => 'nl',
    'NO' => 'no',
    'SE' => 'se',
    'FI' => 'fi',
    'DK' => 'dk',
    'SK' => 'sk',
    'CZ' => 'cs',
    'HU' => 'hu',
    'RO' => 'ro',
    'BG' => 'bg',
    'HR' => 'hr',
    'LT' => 'lt',
    'GR' => 'gr',
    'EE' => 'ee',
    'PT' => 'pt',
    'RU' => 'ru',
    'TR' => 'tr',
    'UA' => 'ua',
    'UAE' => 'ae',
    'KW' => 'ae',
    'QA' => 'ae',
    'SA' => 'ae',
    'OM' => 'ae',
  ],

  'rightPageRead' => [
    'ae',
  ]

];
